### ISSUE TITLE
İzin almadan almış.

### ISSUE THREAD

**Issue by AdemCanCertel** [soulfly34/uptime-bot#1]
@TheClawNz Adlı kişinin alt yapısını izin almadan almışsın ?

**Comment by TheClawNz** [comment]
bot.js dosyasında WhYBoLu development ve benim nicknamem geçiyor evet doğru izinsiz aldı report atın.

**Comment by AdemCanCertel** [comment]
`client.ayarlar = {
  "token": "Nzg1OTc0ODEyNzY1MzIzMjk1.X8_qFg.3Di4uro1wn4lpaA2OEnLFdTwu9I",
  "sahip": ["759095243080597565", "440575579335557121"],
  "prefix": "!",
  "renk": "BLUE",
  "botİsim": "Uptime",
  "embedRenk": "BLUE",
  "embedFooter": "Copyright © WhYBoLu Development 2020",
  "version": "2.5",
  "destek": "https://discord.gg/paypal",
  "website": "https://google.com/"
}
  
client.on("ready", () => {
  console.log("Aktif")
  client.user.setActivity(`Uptime Bot | By TheClawNz#6717`)
})`


Bot.js 8. satır, 24. satır.
